[package]
name = "exloli"
description = "根据指定关键词从 E 站下载本子并上传到 telegraph 并发布到 Telegram 频道"
version = "0.3.0"
authors = ["Aloxaf <aloxafx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 网络相关
libxml = "0.2.12"
reqwest = { version = "0.10.1", features = [ "json", "cookies", "gzip" ]}
tempfile = "3.1.0"
telegram_types = "0.5.0"
v_htmlescape = "0.4.5"

# 配置文件解析
toml = "0.5.6"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.44"

# 杂项
color-backtrace = "0.3.0"
failure = "0.1.5"
lazy_static = "1.4.0"
chrono = "0.4.9"
telegraph-rs = { version = "0.4.0", git = "https://github.com/Aloxaf/telegraph-rs" }
tokio = { version = "0.2.9", features = ["tcp", "time", "rt-threaded", "macros"] }
futures = "0.3.1"

# 日志
log = "0.4.8"
env_logger = "0.7.1"
sled = "0.30.3"

