on:
  push:
    tags:
    - 'v*'

name: Release

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  release-linux:
    name: x86_64-unknown-linux-gnu
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install libxml2 libxml2-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        env:
          RUSTFLAGS: -C lto
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - id: get_name
        run: |
          echo ::set-output name=NAME::exloli-${GITHUB_REF/refs\/tags\//}-x86_64-unknown-linux-gnu.tar.gz
      - run: |
          tar czf ${{ steps.get_name.outputs.NAME }} -C ./target/release exloli
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.get_name.outputs.NAME }}
          asset_name: ${{ steps.get_name.outputs.NAME }}
          asset_content_type: application/zip
